OtelMvcProje/OtelMvcProje/Controllers/MisafirController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using OtelMvcProje.Models.Entity;

namespace OtelMvcProje.Controllers
{
    [Authorize]
    public class MisafirController : Controller
    {
        // GET: Misafir
        MvcOtelProjeEntities3 cb = new MvcOtelProjeEntities3();
        public ActionResult Index()
        {
            var misafirmail = (string)Session["Mail"];
            var misafirbilgi = cb.TblYeniKayit.Where(x => x.Mail == misafirmail).FirstOrDefault();
            return View(misafirbilgi);
        }

        public ActionResult Rezervasyonlarim()
        {
            var misafirmail = (string)Session["Mail"];
            //ViewBag.a = misafirmail;
            var misafirid = cb.TblYeniKayit.Where(x => x.Mail == misafirmail).Select(y => y.ID).FirstOrDefault();
            var degerler = cb.TblRezarvasyon.Where(x => x.Misafir == misafirid).ToList();
            return View(degerler);
        }
        public ActionResult MisafirBilgiGüncelle(TblYeniKayit p)
        {
            var misafir = cb.TblYeniKayit.Find(p.ID);
            misafir.AdSoyad = p.AdSoyad;
            misafir.Şifre= p.Şifre;
            misafir.Telefon = p.Telefon;
            misafir.Mail = p.Mail;
            cb.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("Index", "AnaSayfa");
        }
        public ActionResult GelenMesajlar()
        {
            var misafirmail = (string)Session["Mail"];
            var mesajlar = cb.TblMesaj2.Where(x => x.Alici==misafirmail).ToList();
            return View(mesajlar);
        }
        public ActionResult GidenMesajlar()
        {
            var misafirmail = (string)Session["Mail"];
            var mesajlar = cb.TblMesaj2.Where(x => x.Gonderen == misafirmail).ToList();
            return View(mesajlar);
        }
        public ActionResult MesajDetay(int id)
        {
            
            var mesaj = cb.TblMesaj2.Where(x => x.MesajID == id).FirstOrDefault();
            return View(mesaj);
        }
        [HttpGet]
        public ActionResult YeniMesaj()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniMesaj(TblMesaj2 p)
        {
            var misafirmail = (string)Session["Mail"];
            p.Gonderen = misafirmail;
            p.Alici = "Admin";
            p.Tarih = DateTime.Parse(DateTime.Now.ToShortDateString());
            cb.TblMesaj2.Add(p);
            cb.SaveChanges();
            return RedirectToAction("GidenMesajlar");
        }
    }
}

OtelMvcProje/OtelMvcProje/Views/Misafir/GelenMesajlar.cshtml
@using OtelMvcProje.Models.Entity
@model List<TblMesaj2>
@{
    ViewBag.Title = "GelenMesajlar";
    Layout = "~/Views/Shared/_MisafirLayout.cshtml";
}


<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">

    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <br />
                    <h1>Mesaj Sayfası</h1>
                </div>

            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-3">
                <a href="/Misafir/YeniMesaj/" class="btn btn-primary btn-block mb-3">Yeni Mesaj Oluştur</a>
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Seçenekler</h3>
                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body p-0">
                        <ul class="nav nav-pills flex-column">
                            <li class="nav-item active">
                                <a href="/İletisim/Index/" class="nav-link">
                                    <i class="fas fa-mail-bulk"></i> İletişim
                                    <span class="badge bg-primary float-right">0</span>
                                </a>
                            </li>
                            <li class="nav-item active">
                                <a href="/Misafir/GelenMesajlar/" class="nav-link">
                                    <i class="fas fa-inbox"></i> Gelen Mesajlar
                                    <span class="badge bg-primary float-right">12</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="/Misafir/GidenMesajlar/" class="nav-link">
                                    <i class="far fa-envelope"></i> Gönderilen Mesajlar
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="far fa-file-alt"></i> Taslaklar
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="fas fa-filter"></i> Spam
                                    <span class="badge bg-warning float-right">65</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="far fa-trash-alt"></i> Çöp Kutusu
                                </a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Diğer</h3>
                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body p-0">
                        <ul class="nav nav-pills flex-column">
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="far fa-circle text-danger"></i>
                                    Önemliler

                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="far fa-circle text-warning"></i> Tanıtım
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="far fa-circle text-primary"></i>
                                    Sosyal Medya
                                </a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <div>
            </div>
            <!-- /.col -->
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Gelen Mesajlar</h3>
                        <div class="card-tools">
                            <div class="input-group input-group-sm">
                                <input type="text" class="form-control" placeholder="Mesaj Ara">
                                <div class="input-group-append">
                                    <div class="btn btn-primary">
                                        <i class="fas fa-search"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                <i class="far fa-square"></i>
                            </button>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                            </div>
                            <!-- /.btn-group -->
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                        <div class="table-responsive mailbox-messages">
                            <table class="table table-hover table-striped">
                                <tbody>
                                    @foreach (var item in Model)
                                        {


                                    <tr>
                                        <td>
                                            <div class="icheck-primary">
                                                <input type="checkbox" value="" id="check1">
                                                <label for="check1"></label>
                                            </div>
                                        </td>
                                        <td class="mailbox-star"><a href="/Misafir/MesajDetay/@item.MesajID"><i class="fas fa-star text-warning"></i></a></td>
                                        <td class="mailbox-name"><a href="/Misafir/MesajDetay/@item.MesajID">@item.Gonderen</a></td>
                                        <td class="mailbox-subject">
                                            <b>@item.Konu</b> @item.Mesaj...
                                        </td>
                                        <td class="mailbox-attachment"></td>
                                        <td class="mailbox-date">@(((DateTime)item.Tarih).ToString("dd-MMM-yyyy"))</td>
                                    </tr>
                                    }

                                </tbody>
                            </table>
                            <!-- /.table -->
                        </div>
                        <!-- /.mail-box-messages -->
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                <i class="far fa-square"></i>
                            </button>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                            </div>
                            <!-- /.btn-group -->
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
</body>
</html>

OtelMvcProje/OtelMvcProje/Views/Misafir/Index.cshtml
@model OtelMvcProje.Models.Entity.TblYeniKayit

    @{
        ViewBag.Title = "Index";
        Layout = "~/Views/Shared/_MisafirLayout.cshtml";
    }
@using (Html.BeginForm("MisafirBilgiGüncelle", "Misafir", FormMethod.Post)) {
<br />
    <h2>Profil Sayfası</h2>
    <div class="form-group">
        @Html.HiddenFor(x => x.ID, new { @class = "form-control" })
        @Html.Label("Ad Soyad")
        @Html.TextBoxFor(x => x.AdSoyad, new { @class = "form-control" })
        <br />
        @Html.Label("Telefon")
        @Html.TextBoxFor(x => x.Telefon, new { @class = "form-control" })
        <br /> 
        @Html.Label("Mail")
        @Html.TextBoxFor(x => x.Mail, new { @class = "form-control" })
        <br />
        @Html.Label("Şifre")
        @Html.TextBoxFor(x => x.Şifre, new { @class = "form-control" })
        <br />
        <button class="btn btn-warning">Bilgileri Güncelle</button>
    </div>
}

OtelMvcProje/OtelMvcProje/Views/Misafir/Rezervasyonlarim.cshtml
@using OtelMvcProje.Models.Entity
@model List<TblRezarvasyon>
@{
    ViewBag.Title = "Rezervasyonlarim";
    Layout = "~/Views/Shared/_MisafirLayout.cshtml";
}
<br />
<h2 class="text-info">Rezervasyonlarim</h2>
<br />
<table class="table table-bordered">
    <tr>
        <th>Misafir Adı Soyadı</th>
        <th>Giriş Tarihi</th>
        <th>Çıkış Tarihi</th>
        <th>Kişi</th>    
        <th>Detay</th>    
    </tr>
    @foreach (var item in Model)
    {

  
    <tr>
        <td>@item.TblMisafir.AdSoyad</td>
        <td>@(((DateTime)item.GirisTarihi).ToString("dd-MMM-yyyy"))</td>
        <td>@(((DateTime)item.ÇıkısTarihi).ToString("dd-MMM-yyyy"))</td>
        <td>@item.Kisi</td>
        <td><a href="#" class="btn btn-primary">Detaylar</a></td>
    
    </tr> 
    }
</table>

OtelMvcProje/OtelMvcProje/Views/Misafir/YeniMesaj.cshtml
@model OtelMvcProje.Models.Entity.TblMesaj2
@{
    ViewBag.Title = "YeniMesaj";
    Layout = "~/Views/Shared/_MisafirLayout.cshtml";
}


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Compose Message</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <!-- Theme style -->
    <!-- summernote -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.css">

    <script src="~/AdminLTE-3.0.4/plugins/summernote/summernote.min.js"></script>
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>
<body class="hold-transition sidebar-mini">

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Yeni Mesaj Sayfası</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- /.col -->
                <div class="col-md-3">
                    <a href="/Misafir/YeniMesaj/" class="btn btn-primary btn-block mb-3">Yeni Mesaj Oluştur</a>
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Seçenekler</h3>
                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                    <i class="fas fa-minus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="card-body p-0">
                            <ul class="nav nav-pills flex-column">
                                <li class="nav-item active">
                                    <a href="/İletisim/Index/" class="nav-link">
                                        <i class="fas fa-mail-bulk"></i> İletişim
                                        <span class="badge bg-primary float-right">0</span>
                                    </a>
                                </li>
                                <li class="nav-item active">
                                    <a href="/Misafir/GelenMesajlar/" class="nav-link">
                                        <i class="fas fa-inbox"></i> Gelen Mesajlar
                                        <span class="badge bg-primary float-right">12</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="/Misafir/GidenMesajlar/" class="nav-link">
                                        <i class="far fa-envelope"></i> Gönderilen Mesajlar
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        <i class="far fa-file-alt"></i> Taslaklar
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        <i class="fas fa-filter"></i> Spam
                                        <span class="badge bg-warning float-right">65</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        <i class="far fa-trash-alt"></i> Çöp Kutusu
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Diğer</h3>
                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                    <i class="fas fa-minus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="card-body p-0">
                            <ul class="nav nav-pills flex-column">
                                <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        <i class="far fa-circle text-danger"></i>
                                        Önemliler

                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        <i class="far fa-circle text-warning"></i> Tanıtım
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        <i class="far fa-circle text-primary"></i>
                                        Sosyal Medya
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
                <!-- /.card -->
                <div class="col-md-9">
                    @using (Html.BeginForm("YeniMesaj", "Misafir", FormMethod.Post))
                    {
                        <div class="card card-primary card-outline">
                            <div class="card-header">
                                <h3 class="card-title">Yeni Mesaj Oluştur</h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                @*<div class="form-group">
                                    @Html.Label("Alıcı Adı ")
                                    @Html.TextBoxFor(x => x.Gonderen, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Gonderen)
                                    <br />
                                </div>*@
                                <div class="form-group">
                                    @Html.Label("Konu ")
                                    @Html.TextBoxFor(x => x.Konu, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Konu)
                                    <br />
                                </div>
                                <div class="form-group">
                                    @Html.Label("Mesajınız ")
                                    <textarea id="compose-textarea" name="Mesaj" class="form-control" style="height: 300px">
                                
                    </textarea>
                                </div>
                                <div class="form-group">
                                    <div class="btn btn-default btn-file">
                                        <i class="fas fa-paperclip"></i> Dosya Ekle
                                        <input type="file" name="attachment">
                                    </div>
                                    <p class="help-block">Max. 32MB</p>
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <div class="float-right">
                                    <button type="button" class="btn btn-default"><i class="fas fa-pencil-alt"></i> Taslaklara Kaydet </button>
                                    <button type="submit" class="btn btn-primary"><i class="far fa-envelope"></i> Gönder</button>
                                </div>
                                <button type="reset" class="btn btn-default"><i class="fas fa-times"></i> İptal Et</button>
                            </div>

                            <!-- /.card-footer -->
                        </div>}
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
    <!-- /.content-wrapper -->
    <!-- Control Sidebar -->
    <!-- /.control-sidebar -->
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>
    <!-- Summernote -->
    <script src="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- Page Script -->
    <script src="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.min.js"></script>
    <script>
        $(function () {
            //Add text editor
            $('#compose-textarea').summernote()
        })</script>
</body>
</html>